//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//Agora funcionou Thiagão!

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acao
    {
        public int IdAcao { get; set; }
        public string Acao1 { get; set; }
    }
}
