//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamento
    {
        public Agendamento()
        {
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int IdAgendamento { get; set; }
        public int IdOrcamento { get; set; }
        public System.DateTime DataPrevisao { get; set; }
        public int IdPeriodo { get; set; }
        public string HoraAgendada { get; set; }
        public string HoraIni { get; set; }
        public string HoraFim { get; set; }
        public int IdTecnico { get; set; }
        public int IdLocal { get; set; }
        public int IdDisponibilidade { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Disponibilidade Disponibilidade { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual StatusAgendamento StatusAgendamento { get; set; }
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
