//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficio
    {
        public Beneficio()
        {
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int IdBeneficio { get; set; }
        public int IdFuncionario { get; set; }
        public decimal ValorSalario { get; set; }
        public decimal ValorEncargos { get; set; }
        public Nullable<decimal> ValorBeneficios { get; set; }
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
