//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdCliente { get; set; }
        public Nullable<int> IdTipoCliente { get; set; }
        public Nullable<int> IdProfisao { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DataExpedicao { get; set; }
        public string OrgaoEmissor { get; set; }
        public string CNH { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string EMail { get; set; }
        public string NomeFantasia { get; set; }
        public string RazaoSocial { get; set; }
        public string CNPJ { get; set; }
        public Nullable<int> IdTipoSegmento { get; set; }
        public string AreaAtividade { get; set; }
        public string NomeSocios { get; set; }
        public Nullable<System.DateTime> DataFundacao { get; set; }
        public Nullable<int> NumFuncionarios { get; set; }
        public string InscEsdual { get; set; }
        public string InsMunicipal { get; set; }
        public string Site { get; set; }
        public Nullable<bool> Matriz { get; set; }
        public string GrupoEmpresarial { get; set; }
        public Nullable<int> IdCidade { get; set; }
        public Nullable<int> IdTipoEndereco { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string PontoReferencia { get; set; }
        public string FoneContato { get; set; }
        public string CelContato { get; set; }
        public string FoneComlContato { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Profissao Profissao { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoEndereco TipoEndereco { get; set; }
        public virtual TipoSegmento TipoSegmento { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
