//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientePF
    {
        public int IdClientePF { get; set; }
        public Nullable<int> IdTipoCliente { get; set; }
        public Nullable<int> IdProfisao { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DataExpedicao { get; set; }
        public string OrgaoEmissor { get; set; }
        public string CNH { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string EMail { get; set; }
    }
}
