//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ClientePJ
    {
        [Key]
        public int IdClientePJ { get; set; }
                
        public int IdTipoCliente { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string NomeFantasia { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string RazaoSocial { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]        
        public string CNPJ { get; set; }

        public Nullable<int> IdTipoSegmento { get; set; }
        public string AreaAtividade { get; set; }
        public string NomeSocios { get; set; }
        public Nullable<System.DateTime> DataFundacao { get; set; }
        public Nullable<int> NumFuncionarios { get; set; }
        public string InscEsdual { get; set; }
        public string InsMunicipal { get; set; }
        public string Site { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email inválido.")]
        public string Email { get; set; }
        
        public Nullable<bool> Matriz { get; set; }
        public string GrupoEmpresarial { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public int IdTipoEndereco { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Numero { get; set; }

        public string Complemento { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Bairro { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string CEP { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public int IdEstado { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public int IdCidade { get; set; }
        public string PontoReferencia { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string FoneContato { get; set; }
        public string CelContato { get; set; }
        public string FoneComlContato { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public int Status { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoEndereco TipoEndereco { get; set; }
        public virtual TipoSegmento TipoSegmento { get; set; }
    }
}
