//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int IdDepartamento { get; set; }
        public string Departamento1 { get; set; }
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
