//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPISistemaEntities : DbContext
    {
        public EPISistemaEntities()
            : base("name=EPISistemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Acao> Acao { get; set; }
        public DbSet<Aplicacao> Aplicacao { get; set; }
        public DbSet<AreaAtividade> AreaAtividade { get; set; }
        public DbSet<Beneficio> Beneficio { get; set; }
        public DbSet<Cidade> Cidade { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Diluente> Diluente { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<LocalAplicacao> LocalAplicacao { get; set; }
        public DbSet<LogErro> LogErro { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Nivel> Nivel { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Praga> Praga { get; set; }
        public DbSet<Profissao> Profissao { get; set; }
        public DbSet<RegimeContratacao> RegimeContratacao { get; set; }
        public DbSet<Servico> Servico { get; set; }
        public DbSet<SubMenu> SubMenu { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoPraga> TipoPraga { get; set; }
        public DbSet<TipoServico> TipoServico { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vetor> Vetor { get; set; }
        public DbSet<Agendamento> Agendamento { get; set; }
        public DbSet<Disponibilidade> Disponibilidade { get; set; }
        public DbSet<FormaPagamento> FormaPagamento { get; set; }
        public DbSet<ItemPedido> ItemPedido { get; set; }
        public DbSet<Orcamento> Orcamento { get; set; }
        public DbSet<Pedido> Pedido { get; set; }
        public DbSet<Periodo> Periodo { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<StatusAgendamento> StatusAgendamento { get; set; }
        public DbSet<StatusPedido> StatusPedido { get; set; }
        public DbSet<TipoCliente> TipoCliente { get; set; }
        public DbSet<TipoEndereco> TipoEndereco { get; set; }
        public DbSet<TipoSegmento> TipoSegmento { get; set; }
        public DbSet<ClientePF> ClientePF { get; set; }
    }
}
