//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FormaPagamento
    {
        public FormaPagamento()
        {
            this.Orcamento = new HashSet<Orcamento>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int IdFormaPagamento { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string FormaPagamento1 { get; set; }

        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
