//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdFuncionario { get; set; }
        public string Nome { get; set; }        
        public System.DateTime DataNascimento { get; set; }
        public string Sexo { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string OrgEmissRG { get; set; }
        public System.DateTime DataEmissRG { get; set; }
        public string CNH { get; set; }
        public int IdDepartamento { get; set; }
        public int IdProfissao { get; set; }
        public int IdNivel { get; set; }
        public int IdRegimeContratacao { get; set; }
        public System.DateTime DataAdmissao { get; set; }
        public Nullable<int> IdBeneficio { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual Profissao Profissao { get; set; }
        public virtual RegimeContratacao RegimeContratacao { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
