//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPedido
    {
        public ItemPedido()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdItemPedido { get; set; }
        public int IdListaPedido { get; set; }
        public int IdPraga { get; set; }
        public Nullable<int> IdEnderecoAplicacao { get; set; }
        public int IdLocalAplicacao { get; set; }
        public int IdTipoServico { get; set; }
    
        public virtual LocalAplicacao LocalAplicacao { get; set; }
        public virtual Praga Praga { get; set; }
        public virtual TipoServico TipoServico { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
