//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.SubMenu = new HashSet<SubMenu>();
            this.Perfil = new HashSet<Perfil>();
        }
    
        public int IdMenu { get; set; }
        public string Menu1 { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
    
        public virtual ICollection<SubMenu> SubMenu { get; set; }
        public virtual ICollection<Perfil> Perfil { get; set; }
    }
}
