//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Orcamento
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int IdOrcamento { get; set; }

        public int IdPedido { get; set; }
        public int IdAgendamento { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public decimal ValorOrcamento { get; set; }

        public int IdFormaPagamento { get; set; }
        public int IdProduto { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public System.DateTime DataOrcamento { get; set; }
    
        public virtual Agendamento Agendamento { get; set; }
        public virtual FormaPagamento FormaPagamento { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
