//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
            this.Orcamento = new HashSet<Orcamento>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int IdPedido { get; set; }
        public Nullable<int> IdCliente { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public Nullable<System.DateTime> DtPedido { get; set; }

        public Nullable<int> IdStatusPedido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual ICollection<Orcamento> Orcamento { get; set; }
        public virtual StatusPedido StatusPedido { get; set; }
    }
}
