//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Praga
    {
        public Praga()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
        }
    
        public int IdPraga { get; set; }
        public int IdTipoPraga { get; set; }
        public string NomePraga { get; set; }
        public string ImgPraga { get; set; }
    
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual TipoPraga TipoPraga { get; set; }
    }
}
