//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int IdProduto { get; set; }
        public string NomeProduto { get; set; }
        public int Validade { get; set; }
    
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
