//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public int IdServico { get; set; }
        public int IdCliente { get; set; }
        public int IdPedido { get; set; }
        public System.DateTime DataServico { get; set; }
        public string Periodo { get; set; }
        public int IdTecnico { get; set; }
        public System.DateTime HrInicio { get; set; }
        public System.DateTime HrFim { get; set; }
        public int IdLocal { get; set; }
        public int Status { get; set; }
    }
}
