//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusAgendamento
    {
        public StatusAgendamento()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int IdStatusAgendamento { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Agendamento> Agendamento { get; set; }
    }
}
