//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPedido
    {
        public StatusPedido()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdStatusPedido { get; set; }
        public string StatusPedido1 { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
