//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPraga
    {
        public TipoPraga()
        {
            this.Praga = new HashSet<Praga>();
        }
    
        public int IdTipoPraga { get; set; }
        public string TipoPraga1 { get; set; }
    
        public virtual ICollection<Praga> Praga { get; set; }
    }
}
