//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSegmento
    {
        public TipoSegmento()
        {
            this.ClientePJ = new HashSet<ClientePJ>();
        }
    
        public int IdTipoSegmento { get; set; }
        public string TipoSegmento1 { get; set; }
    
        public virtual ICollection<ClientePJ> ClientePJ { get; set; }
    }
}
