//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCliente
    {
        public TipoCliente()
        {
            this.ClientePF = new HashSet<ClientePF>();
            this.ClientePJ = new HashSet<ClientePJ>();
        }
    
        public int IdTipoCliente { get; set; }
        public string TipoCliente1 { get; set; }
    
        public virtual ICollection<ClientePF> ClientePF { get; set; }
        public virtual ICollection<ClientePJ> ClientePJ { get; set; }
    }
}
