//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServico
    {
        public TipoServico()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
        }
    
        public int IdTipoServico { get; set; }
        public string TipoServico1 { get; set; }
    
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
    }
}
