//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Perfil1 = new HashSet<Perfil>();
        }
    
        public int IdUsuario { get; set; }
        public int IdPerfil { get; set; }
        public int IdFuncionario { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public bool Status { get; set; }
        public bool Bloqueado { get; set; }
        public System.DateTime DataInclusao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<System.DateTime> DataUltimoAcesso { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<Perfil> Perfil1 { get; set; }
    }
}
